// <auto-generated />
using System;
using El1te_Spr1nt_Track_Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace El1te_Spr1nt_Track_Core.Migrations
{
    [DbContext(typeof(El1teDbContext))]
    [Migration("20250616160417_SetDecimalPrecision")]
    partial class SetDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfBirth = new DateTime(2012, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            IsActivated = false,
                            Name = "Michael Doe",
                            ParentUserId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfBirth = new DateTime(2010, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            IsActivated = false,
                            Name = "Emily Smith",
                            ParentUserId = -2
                        });
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.AthleteEvent", b =>
                {
                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AthleteId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("AthleteEvents");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            EventDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "National Stadium",
                            Name = "100m Sprint"
                        },
                        new
                        {
                            Id = -2,
                            EventDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "City Sports Complex",
                            Name = "200m Sprint"
                        });
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Category = "Merchandise",
                            Description = "High-quality club t-shirt",
                            ImageUrl = "tshirt.jpg",
                            Name = "Track Club T-Shirt",
                            Price = 25.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = -2,
                            Category = "Accessories",
                            Description = "Durable sports water bottle",
                            ImageUrl = "waterbottle.jpg",
                            Name = "Water Bottle",
                            Price = 15.99m,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Content = "This club has been amazing for my son!",
                            CreatedAt = new DateTime(2025, 6, 16, 16, 4, 17, 14, DateTimeKind.Utc).AddTicks(1457),
                            IsApproved = false,
                            Name = "John Doe",
                            Role = "Parent"
                        },
                        new
                        {
                            Id = -2,
                            Content = "I've improved so much since joining!",
                            CreatedAt = new DateTime(2025, 6, 16, 16, 4, 17, 14, DateTimeKind.Utc).AddTicks(1460),
                            IsApproved = false,
                            Name = "Emily Smith",
                            Role = "Athlete"
                        });
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(2025, 6, 16, 16, 4, 17, 14, DateTimeKind.Utc).AddTicks(1340),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "hashedpassword123",
                            Role = "Parent"
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(2025, 6, 16, 16, 4, 17, 14, DateTimeKind.Utc).AddTicks(1343),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "hashedpassword456",
                            Role = "Parent"
                        });
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Athlete", b =>
                {
                    b.HasOne("El1te_Spr1nt_Track_Core.Models.User", "ParentUser")
                        .WithMany("Athletes")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("El1te_Spr1nt_Track_Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParentUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.AthleteEvent", b =>
                {
                    b.HasOne("El1te_Spr1nt_Track_Core.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("El1te_Spr1nt_Track_Core.Models.Event", "Event")
                        .WithMany("AthleteEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Event", b =>
                {
                    b.HasOne("El1te_Spr1nt_Track_Core.Models.Athlete", null)
                        .WithMany("Events")
                        .HasForeignKey("AthleteId");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Order", b =>
                {
                    b.HasOne("El1te_Spr1nt_Track_Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.OrderItem", b =>
                {
                    b.HasOne("El1te_Spr1nt_Track_Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("El1te_Spr1nt_Track_Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Athlete", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Event", b =>
                {
                    b.Navigation("AthleteEvents");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("El1te_Spr1nt_Track_Core.Models.User", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
